### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by aaeissa** [anfederico/Stocktalk#1]
I'm receiving import errors after "pip install stocktalk" and "stocktalk-corpus" in a conda environment as well as global install. 

After "from stocktalk import TwitterAxe" attempt:
ImportError: No module named 'TwitterAxe'

**Comment by anfederico** [comment]
Should work, do you have any issue pip installing other packages? Say numpy or pandas?

Also, instead of stocktalk-corpus, try: python -m nltk.downloader vader_lexicon

**Comment by aaeissa** [comment]
Both numpy and pandas are installed and work as expected when I import them in the python interpreter. 

Here's the full error: 

File "/Users/.../anaconda3/lib/python3.5/site-packages/stocktalk/__init__.py", line 1, in <module>
    from TwitterAxe import TwitterAxe
ImportError: No module named 'TwitterAxe'

**Comment by uclatommy** [comment]
I can reproduce this problem on travis: [here's the log](https://travis-ci.org/uclatommy/Stocktalk/jobs/173335741)

**Comment by anfederico** [comment]
Stocktalk is written for python2.7, maybe that's the issue?

**Comment by uclatommy** [comment]
Works with 2.7: [log](https://travis-ci.org/uclatommy/Stocktalk/jobs/173341550)

**Comment by aaeissa** [comment]
Works for py2. Apologies. Did you indicate anywhere in README or requirements? I didn't see anything.

**Comment by anfederico** [comment]
No, my fault, I will make that clear.

**Comment by aaeissa** [comment]
Thanks. Looking forward to checking this out.
