### ISSUE TITLE
streaming.py

### ISSUE THREAD

**Issue by neel17** [anfederico/Stocktalk#10]
Hi,

I am using this beautiful piece of work in one of my project. I want to understand the underlying flow of streaming.py file. 

-       What are the use of differnet functions :
                - get_tracker(queries)
                - get_reverse(queries)
                - elapsed_time(start)
                - process(text)
                - on_status(self, status)
                - streamer()

- 	How and at which part the data from twitter are being pulled? ( with respect to function and class used in it and approach to pick relevant tweets after each refresh interval of 15 min)

-  Is it possible to store the raw tweet as well in the mongodb, instead of storing only the volume and sentiment of the tweets?

-	How the text inputs are being processed?

-	How and where  sentiment analysis is being applied ? 

Kindly help me with these queries!

Thanks,

Neel

**Comment by anfederico** [comment]
Sorry for the late response, been very busy lately.

> How and at which part the data from twitter are being pulled? ( with respect to function and class used in it and approach to pick relevant tweets after each refresh interval of 15 min)

The data is being streamed through tweepy. I have a class called Listener which inherits from tweepy.StreamListener. When the Listener object recieves a tweet, it calls the `on_status` function.

```python
def on_status(self, status):
    original_tweet = status.text 
    ...process tweet
```

> Is it possible to store the raw tweet as well in the mongodb, instead of storing only the volume and sentiment of the tweets?


Sure you'll need to modify the code though.

Store the raw tweets somewhere and when the `process` function is called, modify the call to mongo.

```python
mongio.push(query, 'logs', {'timestamp' : timestamp,
                            'volume'    : volume,
                            'sentiment' : sentiment})
``` 

> How the text inputs are being processed?

Input text is processed like so:

```python
def process(text):
    text = re.sub("[0-9]+", "number", text)
    text = re.sub("#", "", text)
    text = re.sub("\n", "", text)
    text = re.sub("$[^\s]+", "", text)
    text = re.sub("@[^\s]+", "", text)
    text = re.sub("(http|https)://[^\s]*", "", text)
    text = re.sub("[^\s]+@[^\s]+", "", text)
    text = re.sub('[^a-z A-Z]+', '', text)
    return text
```

> How and where sentiment analysis is being applied?

Sentiment analysis is happening here:

```python
processed_tweet = process(original_tweet.lower())
score = SentimentIntensityAnalyzer().polarity_scores(processed_tweet)['compound']
self.tracker[lookup]['scores'].append(score)
```
